[[items]]
name = "ab_glyph"
source = "crates"
categories = ["textrendering"]

[[items]]
name = "alto"
source = "crates"
categories = ["audio"]

[[items]]
name = "AmbientRun/Ambient"
source = "github"
categories = ["engines"]
repository_url = "https://github.com/AmbientRun/Ambient"
homepage_url = "https://www.ambient.run"

[[items]]
name = "ruwren"
description = "A Rustified binding for Wren"
source = "crates"
categories = ["scripting"]
repository_url = "https://github.com/Jengamon/ruwren"
homepage_url = "https://wren.io"
