[[contributors]]
name = "doppioslash"
links = { twitter = "doppioslash", github = "doppioslash", home = "http://doppioslash.com" }
about = "Graphics Programmer"
description = "Writes on <a href=\"//www.shadercat.com\">shadercat.com</a> about Physically Based Shading and Rendering with Rust and Unity."

[[contributors]]
name = "nxnfufunezn"
links = { twitter = "nxnfufunezn", github = "nxnfufunezn" }
about = "Backend developer and FP enthusiast"
