[[contributors]]
name = "Antonin Raffin"
links = { twitter = "araffin2", github = "araffin", home = "https://araffin.github.io/" }
about = ""
description = "Researcher in robotics and machine learning"

[[contributors]]
name = "Freek Stulp"
links = { github = "stulp" }
about = ""
