[[items]]
name = "12 Seconds Awake"
description = "A small 2D top-down physics-based tank war game with worms-like turn mechanics written using Oxygengine"
categories = ["action"]
homepage_url = "//12-seconds-awake.psichix.io"
repository_url = "//github.com/PsichiX/Oxygengine/tree/master/demos/demo-web-game"
image = "/assets/img/12-seconds-awake.jpeg"

[[items]]
name = "A Snake's Tale"
description = "A (100% Rust) puzzle game about snakes in cramped places"
categories = ["puzzle"]
homepage_url = "//m12y.com/a-snakes-tale/"
image = "/assets/img/a-snakes-tale.png"

[[items]]
name = "A/B Street"
description = "A traffic simulation game exploring how small changes to roads affect cyclists, transit users, pedestrians, and drivers"
categories = ["simulation"]
repository_url = "//github.com/dabreegster/abstreet"
image = "/assets/img/ab-street.png"

[[items]]
name = "Apocalypse Post"
description = "a procedurally-generated, turn-based tactical shooter set in a post-apocalyptic future, where you carry mail between survivor camps in your trusty delivery van, all the while fending off attacks from bandits and zombies."
categories = ["strategy", "rpg"]
homepage_url = "//gridbugs.itch.io/apocalypse-post"
repository_url = "//github.com/gridbugs/apocalypse-post"
image = "/assets/img/apocalypse-post.gif"

[[items]]
name = "Ascension 2"
description = "Hop your way through bite sized levels while dodging spikes, turrets, lasers, and more. Then, change the direction of gravity, and do it all again!"
categories = ["platformer"]
homepage_url = "//outkine.itch.io/ascension-2"
repository_url = "//github.com/outkine/ascension-rust"
image = "/assets/img/ascension2.png"

[[items]]
name = "Bitgun"
description = "An action roguelite zombie shooter with difficult and satisfying combat you can learn and master. Guns break quickly and you lose all your gear when you die."
categories = ["action"]
image = "/assets/img/bitgun.gif"
homepage_url = "https://store.steampowered.com/app/1673940/BITGUN"

[[items]]
name = "Boat Journey"
description = "Boat Journey is a turn-based game where you drive a boat through a procedurally-generated landscape on a voyage along a river destined for the ocean. Accept passengers to have them help you on your journey. Fight monsters, collect junk, trade the junk for fuel, use the fuel to travel to the ocean."
categories = ["rpg"]
homepage_url = "//gridbugs.itch.io/boat-journey"
repository_url = "//github.com/gridbugs/boat-journey"
image = "/assets/img/boat-journey.png"
